import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/organisme/Header";
import Sidebar from "@/components/organisme/Sidebar";
import Slide from "@/components/organisme/Slide";
import Slide2 from "@/components/organisme/Slide2";
import Blog from "@/components/organisme/Blog";
import Footer from "@/components/organisme/Footer";
import Messages from "@/components/organisme/Messages";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>INDOMOBIL NISSAN YASMIN | IndomobilGroup.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative">
        <Header></Header>
        <Slide></Slide>
        <Slide2></Slide2>
        <Blog></Blog>
        <Sidebar></Sidebar>
        <Footer></Footer>
        <Messages></Messages>
      </main>
    </>
  );
}
